name: build-verify-package

on:
  push:

jobs:
  build-install:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Add DB configuration to application.properties
        run: |
          echo 'spring.datasource.url=jdbc:postgresql://${{ secrets.DB_HOST_ADDR }}/postgres' >> ./src/main/resources/application.properties
          echo 'spring.datasource.username=${{ secrets.DB_USERNAME }}' >> ./src/main/resources/application.properties
          echo 'spring.datasource.password=${{ secrets.DB_PASSWORD }}' >> ./src/main/resources/application.properties
      - name: Build and Install Spring-Boot app
        run: mvn clean install