name: build-push-docker-image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Add DB configuration to application.properties
        run: |
          echo 'spring.datasource.url=jdbc:postgresql://${{ secrets.DB_HOST_ADDR }}/postgres' >> ./src/main/resources/application.properties
          echo 'spring.datasource.username=${{ secrets.DB_USERNAME }}' >> ./src/main/resources/application.properties
          echo 'spring.datasource.password=${{ secrets.DB_PASSWORD }}' >> ./src/main/resources/application.properties
          echo 'spring.jpa.hibernate.ddl-auto=create-drop' >> ./src/main/resources/application.properties

      - name: Build with Maven
        run: mvn clean install

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Azure Container Registry and Setup Multiarch builder
        run: |
          echo '${{ secrets.CR_PASSWORD }}' | docker login -u ${{ secrets.CR_NAME }} --password-stdin ${{secrets.CR_HOST}}
          BUILDER=buildx-multi-arch
          docker buildx inspect $BUILDER || docker buildx create --name=$BUILDER --driver=docker-container --driver-opt=network=host

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: buildx-multi-arch
          push: true
          tags: ${{ secrets.CR_HOST }}/${{ vars.IMAGE_NAME }}:latest
