# deploy app by using workflow dispatch
name: deploy doctor-agent app

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:

      - name: Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.DEPLOY_HOST}}
          username: ${{secrets.DEPLOY_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          timeout: 1m
          script: |
            sudo docker stop ${{vars.CONTAINER_NAME}}
            sudo docker rm ${{vars.CONTAINER_NAME}}
            sudo docker run --name ${{vars.CONTAINER_NAME}} -p ${{vars.CONTAINER_PORT}}:${{vars.CONTAINER_PORT}} -d --pull always ${{ secrets.CR_HOST }}/${{ vars.IMAGE_NAME }}:latest
